# Use the existing gilleslamiral/imapsync image as a base
FROM gilleslamiral/imapsync:latest

# Set the working directory
WORKDIR /app

# Copy your custom scripts or files into the container

# Install any additional dependencies if needed
# RUN apt-get update && apt-get install -y your-dependencies

# Optionally, you can set environment variables for imapsync
# ENV IMAPSYNC_OPTION1=value1
# ENV IMAPSYNC_OPTION2=value2

# Expose any ports if necessary (not usually needed for imapsync)
# EXPOSE your-port

# Specify the command to run when the container starts
CMD ["imapsync"]
